[package]
name = "hosts_parser"
version = "0.1.0"
authors = ["gatewaynode <44749714+gatewaynode@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
